- hosts: myhost
  collections:
    - community.docker
  become: yes
  tasks:
    - name: Ensure Docker is installed
      ansible.builtin.package:
        name: docker
        state: present

    - name: Start OWASP Juice Shop container
      docker_container:
        name: juiceshop
        image: bkimminich/juice-shop
        ports:
          - "3000:3000"
        state: started
        restart_policy: always
