---
- name: Add VM IP to inventory
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Add host
      add_host:
        hostname: "{{ waflab_vm_ip_address }}"
        groupname: myhost

- hosts: myhost
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker is running
      systemd:
        name: docker
        state: started

    - name: Pull DVWA Docker image
      docker_image:
        name: vulnerables/web-dvwa
        source: pull

    - name: Run DVWA Docker container
      docker_container:
        name: dvwa
        image: vulnerables/web-dvwa
        ports:
          - "3000:80"
        state: started
        restart_policy: always
        env:
          DVWA_PASSWORD: J7r@Q!2zS1pT$8nE
          DB_PASSWORD: 'J7r@Q!2zS1pT$8nE'
          MYSQL_PASS: 'J7r@Q!2zS1pT$8nE'
          DVWA_USER: 'dawsonpaul'










    

  