- name: Start HTTP Server and ngrok
  hosts: localhost
  connection: local
  become: yes
  vars:
    NGROK_TOKEN: "{{ ngrok_token }}"
  tasks:
    - name: Start HTTP Server
      shell: nohup python3 -m http.server 8000 --directory /var/lib/jenkins/reports > http.log 2>&1 &
      args:
        executable: /bin/bash

    - name: Start ngrok
      shell: nohup docker run --network host -e NGROK_AUTHTOKEN={{ NGROK_TOKEN }} -p 4040:4040 ngrok/ngrok http 172.17.0.1:8000 > ngrok.log 2>&1 &
      args:
        executable: /bin/bash